const families = [
  {
    id: 'fam-001',
    familyName: 'Familia Souza',
    responsibleName: 'Ana Souza',
    email: 'ana.souza@email.com',
    phone: '(11) 98888-1111',
    city: 'Sao Paulo',
    createdAt: '2025-11-05T09:00:00Z',
  },
  {
    id: 'fam-002',
    familyName: 'Familia Lima',
    responsibleName: 'Carlos Lima',
    email: 'carlos.lima@email.com',
    phone: '(21) 97777-2222',
    city: 'Rio de Janeiro',
    createdAt: '2025-12-20T12:30:00Z',
  },
];

const children = [
  {
    id: 'child-001',
    familyId: 'fam-001',
    name: 'Livia Souza',
    birthDate: '2022-03-15',
    gender: 'F',
  },
  {
    id: 'child-002',
    familyId: 'fam-001',
    name: 'Rafael Souza',
    birthDate: '2020-09-02',
    gender: 'M',
  },
  {
    id: 'child-003',
    familyId: 'fam-002',
    name: 'Isabela Lima',
    birthDate: '2021-12-08',
    gender: 'F',
  },
  {
    id: 'child-004',
    familyId: 'fam-002',
    name: 'Lucas Lima',
    birthDate: '2024-08-10',
    gender: 'M',
  },
];

const vaccines = [
  {
    id: 'vac-001',
    name: 'Pentavalente',
    disease: 'Difteria, tetano, coqueluche, hepatite B e Haemophilus b',
    notes: 'Vacina de rotina na primeira infancia.',
    active: true,
  },
  {
    id: 'vac-002',
    name: 'Triplice Viral',
    disease: 'Sarampo, caxumba e rubeola',
    notes: 'Reforco importante no calendario infantil.',
    active: true,
  },
  {
    id: 'vac-003',
    name: 'Febre Amarela',
    disease: 'Febre amarela',
    notes: 'Aplicacao conforme orientacao local e faixa etaria.',
    active: true,
  },
  {
    id: 'vac-004',
    name: 'Influenza',
    disease: 'Gripe (influenza)',
    notes: 'Aplicada em campanhas anuais.',
    active: true,
  },
];

const vaccineDoses = [
  {
    id: 'dose-001',
    vaccineId: 'vac-001',
    doseNumber: 1,
    minAgeMonths: 2,
    recommendedUntilMonths: 4,
    minIntervalDays: 60,
  },
  {
    id: 'dose-002',
    vaccineId: 'vac-001',
    doseNumber: 2,
    minAgeMonths: 4,
    recommendedUntilMonths: 6,
    minIntervalDays: 60,
  },
  {
    id: 'dose-003',
    vaccineId: 'vac-002',
    doseNumber: 1,
    minAgeMonths: 12,
    recommendedUntilMonths: 15,
    minIntervalDays: 0,
  },
  {
    id: 'dose-004',
    vaccineId: 'vac-003',
    doseNumber: 1,
    minAgeMonths: 9,
    recommendedUntilMonths: 60,
    minIntervalDays: 0,
  },
  {
    id: 'dose-005',
    vaccineId: 'vac-004',
    doseNumber: 1,
    minAgeMonths: 6,
    recommendedUntilMonths: 120,
    minIntervalDays: 365,
  },
];

const vaccineApplications = [
  {
    id: 'app-001',
    childId: 'child-001',
    vaccineDoseId: 'dose-001',
    scheduledDate: '2022-05-20',
    appliedDate: '2022-05-21',
    batchNumber: 'PENTA-22-001',
    healthUnit: 'UBS Jardim das Flores',
    preVaccinationMapId: 'pvm-001',
    campaignId: null,
  },
  {
    id: 'app-002',
    childId: 'child-001',
    vaccineDoseId: 'dose-002',
    scheduledDate: '2022-07-20',
    appliedDate: null,
    batchNumber: null,
    healthUnit: null,
    preVaccinationMapId: 'pvm-002',
    campaignId: null,
  },
  {
    id: 'app-003',
    childId: 'child-002',
    vaccineDoseId: 'dose-003',
    scheduledDate: '2022-10-10',
    appliedDate: null,
    batchNumber: null,
    healthUnit: null,
    preVaccinationMapId: 'pvm-003',
    campaignId: null,
  },
  {
    id: 'app-004',
    childId: 'child-003',
    vaccineDoseId: 'dose-004',
    scheduledDate: '2023-01-15',
    appliedDate: '2023-01-20',
    batchNumber: 'FA-23-777',
    healthUnit: 'Clinica da Familia Centro',
    preVaccinationMapId: 'pvm-004',
    campaignId: null,
  },
  {
    id: 'app-005',
    childId: 'child-003',
    vaccineDoseId: 'dose-005',
    scheduledDate: '2026-06-15',
    appliedDate: null,
    batchNumber: null,
    healthUnit: null,
    preVaccinationMapId: 'pvm-005',
    campaignId: 'camp-001',
  },
  {
    id: 'app-006',
    childId: 'child-004',
    vaccineDoseId: 'dose-005',
    scheduledDate: '2026-11-10',
    appliedDate: null,
    batchNumber: null,
    healthUnit: null,
    preVaccinationMapId: null,
    campaignId: 'camp-001',
  },
];

const vaccinationCampaigns = [
  {
    id: 'camp-001',
    title: 'Campanha Nacional de Influenza Infantil',
    description: 'Criancas de 6 meses a 10 anos com foco em prevencao de complicacoes respiratorias.',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    targetMinAgeMonths: 6,
    targetMaxAgeMonths: 120,
  },
  {
    id: 'camp-002',
    title: 'Mutirao Regional de Atualizacao da Caderneta',
    description: 'Atualizacao de esquemas em atraso para menores de 7 anos.',
    startDate: '2025-09-01',
    endDate: '2025-10-01',
    targetMinAgeMonths: 0,
    targetMaxAgeMonths: 84,
  },
];

const campaignVaccines = [
  { campaignId: 'camp-001', vaccineId: 'vac-004' },
  { campaignId: 'camp-002', vaccineId: 'vac-001' },
  { campaignId: 'camp-002', vaccineId: 'vac-002' },
];

const preVaccinationMaps = [
  {
    id: 'pvm-001',
    childId: 'child-001',
    vaccineDoseId: 'dose-001',
    filledAt: '2022-05-19T14:20:00Z',
    hadFever: false,
    hasFluSymptoms: false,
    hasAllergyHistory: false,
    isUsingMedication: false,
    hadRecentHospitalization: false,
    observations: 'Sem contraindicacoes aparentes.',
    recommendation: 'CLEAR',
    recommendedBy: 'Enf. Joana P.',
  },
  {
    id: 'pvm-002',
    childId: 'child-001',
    vaccineDoseId: 'dose-002',
    filledAt: '2022-07-19T10:00:00Z',
    hadFever: true,
    hasFluSymptoms: true,
    hasAllergyHistory: false,
    isUsingMedication: true,
    hadRecentHospitalization: false,
    observations: 'Sintomas gripais no dia da triagem. Reavaliar antes de aplicar.',
    recommendation: 'ATTENTION',
    recommendedBy: 'Dra. Patricia N.',
  },
  {
    id: 'pvm-003',
    childId: 'child-002',
    vaccineDoseId: 'dose-003',
    filledAt: '2022-10-10T08:30:00Z',
    hadFever: false,
    hasFluSymptoms: false,
    hasAllergyHistory: true,
    isUsingMedication: false,
    hadRecentHospitalization: false,
    observations: 'Historico alergico leve, sem bloqueio para rotina.',
    recommendation: 'CLEAR',
    recommendedBy: 'Enf. Luiz M.',
  },
  {
    id: 'pvm-004',
    childId: 'child-003',
    vaccineDoseId: 'dose-004',
    filledAt: '2023-01-14T16:00:00Z',
    hadFever: false,
    hasFluSymptoms: false,
    hasAllergyHistory: false,
    isUsingMedication: false,
    hadRecentHospitalization: false,
    observations: 'Fluxo normal de aplicacao.',
    recommendation: 'CLEAR',
    recommendedBy: 'Enf. Clara S.',
  },
  {
    id: 'pvm-005',
    childId: 'child-003',
    vaccineDoseId: 'dose-005',
    filledAt: '2026-06-14T11:10:00Z',
    hadFever: false,
    hasFluSymptoms: false,
    hasAllergyHistory: false,
    isUsingMedication: false,
    hadRecentHospitalization: false,
    observations: 'Elegivel para campanha de influenza.',
    recommendation: 'CLEAR',
    recommendedBy: 'Enf. Luiza T.',
  },
];

module.exports = {
  families,
  children,
  vaccines,
  vaccineDoses,
  vaccineApplications,
  vaccinationCampaigns,
  campaignVaccines,
  preVaccinationMaps,
};
